apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: sales-pvc 
  namespace: sales-test-ns
spec:
  storageclassName: sales-storageclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi